/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Ajout_gest_BV (void);
GtkWidget* create_Supprime_gest_BV (void);
GtkWidget* create_Modifie_gest_BV (void);
GtkWidget* create_Gestion_BV (void);
GtkWidget* create_Login_BV (void);
GtkWidget* create_Accueil (void);
GtkWidget* create_Administrateur (void);
