/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Ajout_gest_BV (void);
GtkWidget* create_Supprime_gest_BV (void);
GtkWidget* create_Modifie_gest_BV (void);
GtkWidget* create_Gestion_BV (void);
GtkWidget* create_Login_BV (void);
GtkWidget* create_Accueil (void);
GtkWidget* create_Administrateur (void);
GtkWidget* create_Gestion_Reclamation (void);
GtkWidget* create_Ajout_gest_rec (void);
GtkWidget* create_Modifie_gest_rec (void);
GtkWidget* create_Supprimer_ges_rec (void);
GtkWidget* create_fct1_fedi (void);
GtkWidget* create_fct2_fedi (void);
GtkWidget* create_login_rec (void);
GtkWidget* create_Login_election (void);
GtkWidget* create_Gestion_des_elections (void);
GtkWidget* create_Ajout_gest_elec (void);
GtkWidget* create_Modifie_gest_elec (void);
GtkWidget* create_supp_gest_elec (void);
GtkWidget* create_window_Taux1_electeur (void);
GtkWidget* create_window_Taux2_HF (void);
