/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Ajout_gest_BV (void)
{
  GtkWidget *Ajout_gest_BV;
  GtkWidget *fixed22;
  GtkWidget *entry_id_AB_ajout_BV;
  GtkWidget *label122;
  GtkWidget *entry_Id_ajout_BV;
  GtkObject *spinbutton_nB_ajout_BV_adj;
  GtkWidget *spinbutton_nB_ajout_BV;
  GtkWidget *button_retour15;
  GtkWidget *alignment78;
  GtkWidget *hbox70;
  GtkWidget *image89;
  GtkWidget *label131;
  GtkObject *spinbutton_cO_ajout_BV_adj;
  GtkWidget *spinbutton_cO_ajout_BV;
  GtkWidget *label124;
  GtkWidget *label125;
  GtkWidget *label127;
  GtkWidget *label121;
  GtkWidget *combobox_ajout_BV;
  GtkWidget *checkbutton_ajout_BV;
  GtkWidget *Annuler_ajout_BV;
  GtkWidget *alignment77;
  GtkWidget *hbox69;
  GtkWidget *image88;
  GtkWidget *label130;
  GtkWidget *Enregistrer_ajout_BV;
  GtkWidget *alignment76;
  GtkWidget *hbox68;
  GtkWidget *image87;
  GtkWidget *label129;
  GtkWidget *label_aj;
  GtkWidget *Ajout_Bureau_de_Vote;
  GtkWidget *label128;
  GtkWidget *quitter10;
  GtkWidget *alignment79;
  GtkWidget *hbox71;
  GtkWidget *image90;
  GtkWidget *label132;

  Ajout_gest_BV = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Ajout_gest_BV, 800, 544);
  gtk_window_set_title (GTK_WINDOW (Ajout_gest_BV), _("Ajout_gest_BV"));

  fixed22 = gtk_fixed_new ();
  gtk_widget_show (fixed22);
  gtk_container_add (GTK_CONTAINER (Ajout_gest_BV), fixed22);

  entry_id_AB_ajout_BV = gtk_entry_new ();
  gtk_widget_show (entry_id_AB_ajout_BV);
  gtk_fixed_put (GTK_FIXED (fixed22), entry_id_AB_ajout_BV, 392, 96);
  gtk_widget_set_size_request (entry_id_AB_ajout_BV, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_AB_ajout_BV), 8226);

  label122 = gtk_label_new ("");
  gtk_widget_show (label122);
  gtk_fixed_put (GTK_FIXED (fixed22), label122, 272, 40);
  gtk_widget_set_size_request (label122, 57, 17);

  entry_Id_ajout_BV = gtk_entry_new ();
  gtk_widget_show (entry_Id_ajout_BV);
  gtk_fixed_put (GTK_FIXED (fixed22), entry_Id_ajout_BV, 392, 320);
  gtk_widget_set_size_request (entry_Id_ajout_BV, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_Id_ajout_BV), 8226);

  spinbutton_nB_ajout_BV_adj = gtk_adjustment_new (1, 1, 1000, 1, 10, 10);
  spinbutton_nB_ajout_BV = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_nB_ajout_BV_adj), 1, 0);
  gtk_widget_show (spinbutton_nB_ajout_BV);
  gtk_fixed_put (GTK_FIXED (fixed22), spinbutton_nB_ajout_BV, 392, 152);
  gtk_widget_set_size_request (spinbutton_nB_ajout_BV, 60, 32);

  button_retour15 = gtk_button_new ();
  gtk_widget_show (button_retour15);
  gtk_fixed_put (GTK_FIXED (fixed22), button_retour15, 8, 8);
  gtk_widget_set_size_request (button_retour15, 74, 29);

  alignment78 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment78);
  gtk_container_add (GTK_CONTAINER (button_retour15), alignment78);

  hbox70 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox70);
  gtk_container_add (GTK_CONTAINER (alignment78), hbox70);

  image89 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image89);
  gtk_box_pack_start (GTK_BOX (hbox70), image89, FALSE, FALSE, 0);

  label131 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label131);
  gtk_box_pack_start (GTK_BOX (hbox70), label131, FALSE, FALSE, 0);

  spinbutton_cO_ajout_BV_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton_cO_ajout_BV = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_cO_ajout_BV_adj), 1, 0);
  gtk_widget_show (spinbutton_cO_ajout_BV);
  gtk_fixed_put (GTK_FIXED (fixed22), spinbutton_cO_ajout_BV, 392, 208);
  gtk_widget_set_size_request (spinbutton_cO_ajout_BV, 60, 32);

  label124 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">Capacit\303\251 observateurs :</span></b>    "));
  gtk_widget_show (label124);
  gtk_fixed_put (GTK_FIXED (fixed22), label124, 160, 208);
  gtk_widget_set_size_request (label124, 224, 32);
  gtk_label_set_use_markup (GTK_LABEL (label124), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (label124), TRUE);

  label125 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">Capacit\303\251 \303\251lecteurs :</span></b>    "));
  gtk_widget_show (label125);
  gtk_fixed_put (GTK_FIXED (fixed22), label125, 160, 152);
  gtk_widget_set_size_request (label125, 224, 32);
  gtk_label_set_use_markup (GTK_LABEL (label125), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (label125), TRUE);

  label127 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">Adresse :</span></b>    "));
  gtk_widget_show (label127);
  gtk_fixed_put (GTK_FIXED (fixed22), label127, 160, 264);
  gtk_widget_set_size_request (label127, 96, 25);
  gtk_label_set_use_markup (GTK_LABEL (label127), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (label127), TRUE);

  label121 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">Identifiant de l'agent :</span></b>    "));
  gtk_widget_show (label121);
  gtk_fixed_put (GTK_FIXED (fixed22), label121, 160, 320);
  gtk_widget_set_size_request (label121, 244, 32);
  gtk_label_set_use_markup (GTK_LABEL (label121), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (label121), TRUE);

  combobox_ajout_BV = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_ajout_BV);
  gtk_fixed_put (GTK_FIXED (fixed22), combobox_ajout_BV, 392, 264);
  gtk_widget_set_size_request (combobox_ajout_BV, 200, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout_BV), _("Gabes_sud"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout_BV), _("Gabes_nord"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout_BV), _("Gabes_Elmadina"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout_BV), _("Gabes_ouest "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout_BV), _("Gabes_est"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout_BV), _("Chneni"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout_BV), _("Ghanouch"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout_BV), _("Metouia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout_BV), _("Wedhref"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout_BV), _("Mareth"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_ajout_BV), _("Matmata"));

  checkbutton_ajout_BV = gtk_check_button_new_with_mnemonic (_("Accepter les conditions generales"));
  gtk_widget_show (checkbutton_ajout_BV);
  gtk_fixed_put (GTK_FIXED (fixed22), checkbutton_ajout_BV, 256, 376);
  gtk_widget_set_size_request (checkbutton_ajout_BV, 280, 40);

  Annuler_ajout_BV = gtk_button_new ();
  gtk_widget_show (Annuler_ajout_BV);
  gtk_fixed_put (GTK_FIXED (fixed22), Annuler_ajout_BV, 488, 488);
  gtk_widget_set_size_request (Annuler_ajout_BV, 120, 37);

  alignment77 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment77);
  gtk_container_add (GTK_CONTAINER (Annuler_ajout_BV), alignment77);

  hbox69 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox69);
  gtk_container_add (GTK_CONTAINER (alignment77), hbox69);

  image88 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image88);
  gtk_box_pack_start (GTK_BOX (hbox69), image88, FALSE, FALSE, 0);

  label130 = gtk_label_new_with_mnemonic (_("  <span color=\"red\">Annuler</span>  "));
  gtk_widget_show (label130);
  gtk_box_pack_start (GTK_BOX (hbox69), label130, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label130), TRUE);

  Enregistrer_ajout_BV = gtk_button_new ();
  gtk_widget_show (Enregistrer_ajout_BV);
  gtk_fixed_put (GTK_FIXED (fixed22), Enregistrer_ajout_BV, 336, 488);
  gtk_widget_set_size_request (Enregistrer_ajout_BV, 120, 37);

  alignment76 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment76);
  gtk_container_add (GTK_CONTAINER (Enregistrer_ajout_BV), alignment76);

  hbox68 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox68);
  gtk_container_add (GTK_CONTAINER (alignment76), hbox68);

  image87 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image87);
  gtk_box_pack_start (GTK_BOX (hbox68), image87, FALSE, FALSE, 0);

  label129 = gtk_label_new_with_mnemonic (_("  <span color=\"green\">Enregistrer </span>    "));
  gtk_widget_show (label129);
  gtk_box_pack_start (GTK_BOX (hbox68), label129, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label129), TRUE);

  label_aj = gtk_label_new ("");
  gtk_widget_show (label_aj);
  gtk_fixed_put (GTK_FIXED (fixed22), label_aj, 144, 424);
  gtk_widget_set_size_request (label_aj, 488, 49);

  Ajout_Bureau_de_Vote = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">AJOUTER BUREAU DE VOTE :</span></b>    "));
  gtk_widget_show (Ajout_Bureau_de_Vote);
  gtk_fixed_put (GTK_FIXED (fixed22), Ajout_Bureau_de_Vote, 264, 16);
  gtk_widget_set_size_request (Ajout_Bureau_de_Vote, 256, 40);
  gtk_label_set_use_markup (GTK_LABEL (Ajout_Bureau_de_Vote), TRUE);

  label128 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">Identifiant du bureau :</span></b>    "));
  gtk_widget_show (label128);
  gtk_fixed_put (GTK_FIXED (fixed22), label128, 160, 96);
  gtk_widget_set_size_request (label128, 208, 41);
  gtk_label_set_use_markup (GTK_LABEL (label128), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (label128), TRUE);

  quitter10 = gtk_button_new ();
  gtk_widget_show (quitter10);
  gtk_fixed_put (GTK_FIXED (fixed22), quitter10, 688, 8);
  gtk_widget_set_size_request (quitter10, 88, 30);

  alignment79 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment79);
  gtk_container_add (GTK_CONTAINER (quitter10), alignment79);

  hbox71 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox71);
  gtk_container_add (GTK_CONTAINER (alignment79), hbox71);
  gtk_widget_set_size_request (hbox71, 74, 28);

  image90 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image90);
  gtk_box_pack_start (GTK_BOX (hbox71), image90, FALSE, FALSE, 0);

  label132 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label132);
  gtk_box_pack_start (GTK_BOX (hbox71), label132, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label132, 55, -1);

  g_signal_connect ((gpointer) button_retour15, "clicked",
                    G_CALLBACK (on_button_retour15_clicked),
                    NULL);
  g_signal_connect ((gpointer) checkbutton_ajout_BV, "toggled",
                    G_CALLBACK (on_checkbutton_ajout_BV_toggled),
                    NULL);
  g_signal_connect ((gpointer) Annuler_ajout_BV, "clicked",
                    G_CALLBACK (on_Annuler_ajout_BV_clicked),
                    NULL);
  g_signal_connect ((gpointer) Enregistrer_ajout_BV, "clicked",
                    G_CALLBACK (on_Enregistrer_ajout_BV_clicked),
                    NULL);
  g_signal_connect ((gpointer) quitter10, "clicked",
                    G_CALLBACK (on_quitter10_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label124), spinbutton_cO_ajout_BV);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label125), spinbutton_nB_ajout_BV);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label121), entry_Id_ajout_BV);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label128), entry_id_AB_ajout_BV);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajout_gest_BV, Ajout_gest_BV, "Ajout_gest_BV");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, fixed22, "fixed22");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, entry_id_AB_ajout_BV, "entry_id_AB_ajout_BV");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, label122, "label122");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, entry_Id_ajout_BV, "entry_Id_ajout_BV");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, spinbutton_nB_ajout_BV, "spinbutton_nB_ajout_BV");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, button_retour15, "button_retour15");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, alignment78, "alignment78");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, hbox70, "hbox70");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, image89, "image89");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, label131, "label131");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, spinbutton_cO_ajout_BV, "spinbutton_cO_ajout_BV");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, label124, "label124");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, label125, "label125");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, label127, "label127");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, label121, "label121");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, combobox_ajout_BV, "combobox_ajout_BV");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, checkbutton_ajout_BV, "checkbutton_ajout_BV");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, Annuler_ajout_BV, "Annuler_ajout_BV");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, alignment77, "alignment77");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, hbox69, "hbox69");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, image88, "image88");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, label130, "label130");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, Enregistrer_ajout_BV, "Enregistrer_ajout_BV");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, alignment76, "alignment76");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, hbox68, "hbox68");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, image87, "image87");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, label129, "label129");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, label_aj, "label_aj");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, Ajout_Bureau_de_Vote, "Ajout_Bureau_de_Vote");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, label128, "label128");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, quitter10, "quitter10");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, alignment79, "alignment79");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, hbox71, "hbox71");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, image90, "image90");
  GLADE_HOOKUP_OBJECT (Ajout_gest_BV, label132, "label132");

  return Ajout_gest_BV;
}

GtkWidget*
create_Supprime_gest_BV (void)
{
  GtkWidget *Supprime_gest_BV;
  GtkWidget *fixed24;
  GtkWidget *entry_id_BV_supp_BV;
  GtkWidget *button_retour_supp;
  GtkWidget *alignment124;
  GtkWidget *hbox116;
  GtkWidget *image135;
  GtkWidget *label314;
  GtkWidget *fixed30;
  GtkWidget *label339;
  GtkWidget *label312;
  GtkWidget *Supprimer_supp_BV;
  GtkWidget *alignment134;
  GtkWidget *hbox126;
  GtkWidget *image145;
  GtkWidget *label340;
  GtkWidget *radiobutton_supp_non;
  GSList *radiobutton_supp_non_group = NULL;
  GtkWidget *radiobutton_supp_oui;
  GtkWidget *label374;

  Supprime_gest_BV = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Supprime_gest_BV, 800, 544);
  gtk_window_set_title (GTK_WINDOW (Supprime_gest_BV), _("Supprime_gest_BV"));

  fixed24 = gtk_fixed_new ();
  gtk_widget_show (fixed24);
  gtk_container_add (GTK_CONTAINER (Supprime_gest_BV), fixed24);
  gtk_widget_set_size_request (fixed24, 608, 325);

  entry_id_BV_supp_BV = gtk_entry_new ();
  gtk_widget_show (entry_id_BV_supp_BV);
  gtk_fixed_put (GTK_FIXED (fixed24), entry_id_BV_supp_BV, 376, 120);
  gtk_widget_set_size_request (entry_id_BV_supp_BV, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_BV_supp_BV), 8226);

  button_retour_supp = gtk_button_new ();
  gtk_widget_show (button_retour_supp);
  gtk_fixed_put (GTK_FIXED (fixed24), button_retour_supp, 16, 8);
  gtk_widget_set_size_request (button_retour_supp, 80, 29);

  alignment124 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment124);
  gtk_container_add (GTK_CONTAINER (button_retour_supp), alignment124);

  hbox116 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox116);
  gtk_container_add (GTK_CONTAINER (alignment124), hbox116);

  image135 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image135);
  gtk_box_pack_start (GTK_BOX (hbox116), image135, FALSE, FALSE, 0);

  label314 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label314);
  gtk_box_pack_start (GTK_BOX (hbox116), label314, FALSE, FALSE, 0);

  fixed30 = gtk_fixed_new ();
  gtk_widget_show (fixed30);
  gtk_fixed_put (GTK_FIXED (fixed24), fixed30, 0, 0);
  gtk_widget_set_size_request (fixed30, 0, 0);

  label339 = gtk_label_new_with_mnemonic (_(" <b><span color=\"black\">Supprimer un Bureau</span></b>  "));
  gtk_widget_show (label339);
  gtk_fixed_put (GTK_FIXED (fixed24), label339, 304, 8);
  gtk_widget_set_size_request (label339, 192, 33);
  gtk_label_set_use_markup (GTK_LABEL (label339), TRUE);

  label312 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">IDENTIFIANT :</span></b>   "));
  gtk_widget_show (label312);
  gtk_fixed_put (GTK_FIXED (fixed24), label312, 248, 120);
  gtk_widget_set_size_request (label312, 104, 33);
  gtk_label_set_use_markup (GTK_LABEL (label312), TRUE);

  Supprimer_supp_BV = gtk_button_new ();
  gtk_widget_show (Supprimer_supp_BV);
  gtk_fixed_put (GTK_FIXED (fixed24), Supprimer_supp_BV, 336, 352);
  gtk_widget_set_size_request (Supprimer_supp_BV, 136, 37);

  alignment134 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment134);
  gtk_container_add (GTK_CONTAINER (Supprimer_supp_BV), alignment134);

  hbox126 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox126);
  gtk_container_add (GTK_CONTAINER (alignment134), hbox126);

  image145 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image145);
  gtk_box_pack_start (GTK_BOX (hbox126), image145, FALSE, FALSE, 0);

  label340 = gtk_label_new_with_mnemonic (_("  <span color=\"red\">Supprime</span>"));
  gtk_widget_show (label340);
  gtk_box_pack_start (GTK_BOX (hbox126), label340, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label340), TRUE);

  radiobutton_supp_non = gtk_radio_button_new_with_mnemonic (NULL, _("Non"));
  gtk_widget_show (radiobutton_supp_non);
  gtk_fixed_put (GTK_FIXED (fixed24), radiobutton_supp_non, 440, 272);
  gtk_widget_set_size_request (radiobutton_supp_non, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_supp_non), radiobutton_supp_non_group);
  radiobutton_supp_non_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_supp_non));

  radiobutton_supp_oui = gtk_radio_button_new_with_mnemonic (NULL, _("Oui"));
  gtk_widget_show (radiobutton_supp_oui);
  gtk_fixed_put (GTK_FIXED (fixed24), radiobutton_supp_oui, 296, 272);
  gtk_widget_set_size_request (radiobutton_supp_oui, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton_supp_oui), radiobutton_supp_non_group);
  radiobutton_supp_non_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton_supp_oui));

  label374 = gtk_label_new_with_mnemonic (_("<b><span color=\"red\">\303\212tes-vous s\303\273r de vouloir supprimer ce bureau de vote ?</span></b>    "));
  gtk_widget_show (label374);
  gtk_fixed_put (GTK_FIXED (fixed24), label374, 192, 200);
  gtk_widget_set_size_request (label374, 424, 49);
  gtk_label_set_use_markup (GTK_LABEL (label374), TRUE);

  g_signal_connect ((gpointer) button_retour_supp, "clicked",
                    G_CALLBACK (on_button_retour_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) Supprimer_supp_BV, "clicked",
                    G_CALLBACK (on_Supprimer_supp_BV_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_supp_non, "toggled",
                    G_CALLBACK (on_radiobutton_supp_non_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton_supp_oui, "toggled",
                    G_CALLBACK (on_radiobutton_supp_oui_toggled),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label312), entry_id_BV_supp_BV);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Supprime_gest_BV, Supprime_gest_BV, "Supprime_gest_BV");
  GLADE_HOOKUP_OBJECT (Supprime_gest_BV, fixed24, "fixed24");
  GLADE_HOOKUP_OBJECT (Supprime_gest_BV, entry_id_BV_supp_BV, "entry_id_BV_supp_BV");
  GLADE_HOOKUP_OBJECT (Supprime_gest_BV, button_retour_supp, "button_retour_supp");
  GLADE_HOOKUP_OBJECT (Supprime_gest_BV, alignment124, "alignment124");
  GLADE_HOOKUP_OBJECT (Supprime_gest_BV, hbox116, "hbox116");
  GLADE_HOOKUP_OBJECT (Supprime_gest_BV, image135, "image135");
  GLADE_HOOKUP_OBJECT (Supprime_gest_BV, label314, "label314");
  GLADE_HOOKUP_OBJECT (Supprime_gest_BV, fixed30, "fixed30");
  GLADE_HOOKUP_OBJECT (Supprime_gest_BV, label339, "label339");
  GLADE_HOOKUP_OBJECT (Supprime_gest_BV, label312, "label312");
  GLADE_HOOKUP_OBJECT (Supprime_gest_BV, Supprimer_supp_BV, "Supprimer_supp_BV");
  GLADE_HOOKUP_OBJECT (Supprime_gest_BV, alignment134, "alignment134");
  GLADE_HOOKUP_OBJECT (Supprime_gest_BV, hbox126, "hbox126");
  GLADE_HOOKUP_OBJECT (Supprime_gest_BV, image145, "image145");
  GLADE_HOOKUP_OBJECT (Supprime_gest_BV, label340, "label340");
  GLADE_HOOKUP_OBJECT (Supprime_gest_BV, radiobutton_supp_non, "radiobutton_supp_non");
  GLADE_HOOKUP_OBJECT (Supprime_gest_BV, radiobutton_supp_oui, "radiobutton_supp_oui");
  GLADE_HOOKUP_OBJECT (Supprime_gest_BV, label374, "label374");

  return Supprime_gest_BV;
}

GtkWidget*
create_Modifie_gest_BV (void)
{
  GtkWidget *Modifie_gest_BV;
  GtkWidget *fixed25;
  GtkWidget *entry_id_modifie_BV;
  GtkWidget *label315;
  GtkWidget *entry_id_AB_modifie_BV;
  GtkObject *spinbutton_cb_modifie_BV_adj;
  GtkWidget *spinbutton_cb_modifie_BV;
  GtkObject *spinbutton_nb_modifie_BV_adj;
  GtkWidget *spinbutton_nb_modifie_BV;
  GtkWidget *label325;
  GtkWidget *label321;
  GtkWidget *label320;
  GtkWidget *label322;
  GtkWidget *label323;
  GtkWidget *label319;
  GtkWidget *combobox_modifie_BV;
  GtkWidget *Annuler_modifie_BV;
  GtkWidget *alignment127;
  GtkWidget *hbox119;
  GtkWidget *image138;
  GtkWidget *label318;
  GtkWidget *Enregistrer_modifie_BV;
  GtkWidget *alignment128;
  GtkWidget *hbox120;
  GtkWidget *image139;
  GtkWidget *label324;
  GtkWidget *Verifier_modifie_BV;
  GtkWidget *alignment158;
  GtkWidget *hbox150;
  GtkWidget *image169;
  GtkWidget *label375;
  GtkWidget *button_retour_16;
  GtkWidget *alignment125;
  GtkWidget *hbox117;
  GtkWidget *image136;
  GtkWidget *label316;
  GtkWidget *quitter_mod;
  GtkWidget *alignment126;
  GtkWidget *hbox118;
  GtkWidget *image137;
  GtkWidget *label317;

  Modifie_gest_BV = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Modifie_gest_BV, 800, 544);
  gtk_window_set_title (GTK_WINDOW (Modifie_gest_BV), _("Modifie_gest_BV"));

  fixed25 = gtk_fixed_new ();
  gtk_widget_show (fixed25);
  gtk_container_add (GTK_CONTAINER (Modifie_gest_BV), fixed25);

  entry_id_modifie_BV = gtk_entry_new ();
  gtk_widget_show (entry_id_modifie_BV);
  gtk_fixed_put (GTK_FIXED (fixed25), entry_id_modifie_BV, 360, 96);
  gtk_widget_set_size_request (entry_id_modifie_BV, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_modifie_BV), 8226);

  label315 = gtk_label_new ("");
  gtk_widget_show (label315);
  gtk_fixed_put (GTK_FIXED (fixed25), label315, 272, 40);
  gtk_widget_set_size_request (label315, 57, 17);

  entry_id_AB_modifie_BV = gtk_entry_new ();
  gtk_widget_show (entry_id_AB_modifie_BV);
  gtk_fixed_put (GTK_FIXED (fixed25), entry_id_AB_modifie_BV, 360, 320);
  gtk_widget_set_size_request (entry_id_AB_modifie_BV, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_id_AB_modifie_BV), 8226);

  spinbutton_cb_modifie_BV_adj = gtk_adjustment_new (1, 1, 1000, 1, 10, 10);
  spinbutton_cb_modifie_BV = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_cb_modifie_BV_adj), 1, 0);
  gtk_widget_show (spinbutton_cb_modifie_BV);
  gtk_fixed_put (GTK_FIXED (fixed25), spinbutton_cb_modifie_BV, 360, 152);
  gtk_widget_set_size_request (spinbutton_cb_modifie_BV, 60, 32);

  spinbutton_nb_modifie_BV_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinbutton_nb_modifie_BV = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_nb_modifie_BV_adj), 1, 0);
  gtk_widget_show (spinbutton_nb_modifie_BV);
  gtk_fixed_put (GTK_FIXED (fixed25), spinbutton_nb_modifie_BV, 360, 208);
  gtk_widget_set_size_request (spinbutton_nb_modifie_BV, 60, 32);

  label325 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">MODIFIER BUREAU DE VOTE :</span></b>    "));
  gtk_widget_show (label325);
  gtk_fixed_put (GTK_FIXED (fixed25), label325, 240, 16);
  gtk_widget_set_size_request (label325, 256, 40);
  gtk_label_set_use_markup (GTK_LABEL (label325), TRUE);

  label321 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">Capacit\303\251 \303\251lecteurs :</span></b>    "));
  gtk_widget_show (label321);
  gtk_fixed_put (GTK_FIXED (fixed25), label321, 136, 152);
  gtk_widget_set_size_request (label321, 224, 32);
  gtk_label_set_use_markup (GTK_LABEL (label321), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (label321), TRUE);

  label320 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">Capacit\303\251 observateurs :</span></b>    "));
  gtk_widget_show (label320);
  gtk_fixed_put (GTK_FIXED (fixed25), label320, 136, 208);
  gtk_widget_set_size_request (label320, 224, 32);
  gtk_label_set_use_markup (GTK_LABEL (label320), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (label320), TRUE);

  label322 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">Adresse :</span></b>    "));
  gtk_widget_show (label322);
  gtk_fixed_put (GTK_FIXED (fixed25), label322, 136, 264);
  gtk_widget_set_size_request (label322, 96, 25);
  gtk_label_set_use_markup (GTK_LABEL (label322), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (label322), TRUE);

  label323 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">Identifiant de l'agent :</span></b>    "));
  gtk_widget_show (label323);
  gtk_fixed_put (GTK_FIXED (fixed25), label323, 136, 320);
  gtk_widget_set_size_request (label323, 244, 32);
  gtk_label_set_use_markup (GTK_LABEL (label323), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (label323), TRUE);

  label319 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">Identifiant du bureau :</span></b>    "));
  gtk_widget_show (label319);
  gtk_fixed_put (GTK_FIXED (fixed25), label319, 136, 96);
  gtk_widget_set_size_request (label319, 208, 41);
  gtk_label_set_use_markup (GTK_LABEL (label319), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (label319), TRUE);

  combobox_modifie_BV = gtk_combo_box_new_text ();
  gtk_widget_show (combobox_modifie_BV);
  gtk_fixed_put (GTK_FIXED (fixed25), combobox_modifie_BV, 360, 264);
  gtk_widget_set_size_request (combobox_modifie_BV, 200, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_modifie_BV), _("Gabes_sud"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_modifie_BV), _("Gabes_nord"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_modifie_BV), _("Gabes_Elmadina"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_modifie_BV), _("Gabes_ouest "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_modifie_BV), _("Gabes_est"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_modifie_BV), _("Chneni"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_modifie_BV), _("Ghanouch"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_modifie_BV), _("Metouia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_modifie_BV), _("Wedhref"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_modifie_BV), _("Mareth"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox_modifie_BV), _("Matmata"));

  Annuler_modifie_BV = gtk_button_new ();
  gtk_widget_show (Annuler_modifie_BV);
  gtk_fixed_put (GTK_FIXED (fixed25), Annuler_modifie_BV, 416, 448);
  gtk_widget_set_size_request (Annuler_modifie_BV, 120, 37);

  alignment127 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment127);
  gtk_container_add (GTK_CONTAINER (Annuler_modifie_BV), alignment127);

  hbox119 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox119);
  gtk_container_add (GTK_CONTAINER (alignment127), hbox119);

  image138 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image138);
  gtk_box_pack_start (GTK_BOX (hbox119), image138, FALSE, FALSE, 0);

  label318 = gtk_label_new_with_mnemonic (_("  <span color=\"red\">Annuler</span>"));
  gtk_widget_show (label318);
  gtk_box_pack_start (GTK_BOX (hbox119), label318, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label318), TRUE);

  Enregistrer_modifie_BV = gtk_button_new ();
  gtk_widget_show (Enregistrer_modifie_BV);
  gtk_fixed_put (GTK_FIXED (fixed25), Enregistrer_modifie_BV, 224, 448);
  gtk_widget_set_size_request (Enregistrer_modifie_BV, 120, 37);

  alignment128 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment128);
  gtk_container_add (GTK_CONTAINER (Enregistrer_modifie_BV), alignment128);

  hbox120 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox120);
  gtk_container_add (GTK_CONTAINER (alignment128), hbox120);

  image139 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image139);
  gtk_box_pack_start (GTK_BOX (hbox120), image139, FALSE, FALSE, 0);

  label324 = gtk_label_new_with_mnemonic (_("  <span color=\"green\">Enregistrer</span>"));
  gtk_widget_show (label324);
  gtk_box_pack_start (GTK_BOX (hbox120), label324, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label324), TRUE);

  Verifier_modifie_BV = gtk_button_new ();
  gtk_widget_show (Verifier_modifie_BV);
  gtk_fixed_put (GTK_FIXED (fixed25), Verifier_modifie_BV, 616, 96);
  gtk_widget_set_size_request (Verifier_modifie_BV, 104, 29);

  alignment158 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment158);
  gtk_container_add (GTK_CONTAINER (Verifier_modifie_BV), alignment158);

  hbox150 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox150);
  gtk_container_add (GTK_CONTAINER (alignment158), hbox150);

  image169 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image169);
  gtk_box_pack_start (GTK_BOX (hbox150), image169, FALSE, FALSE, 0);

  label375 = gtk_label_new_with_mnemonic (_("  <span color=\"blue\">Verifier</span>"));
  gtk_widget_show (label375);
  gtk_box_pack_start (GTK_BOX (hbox150), label375, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label375), TRUE);

  button_retour_16 = gtk_button_new ();
  gtk_widget_show (button_retour_16);
  gtk_fixed_put (GTK_FIXED (fixed25), button_retour_16, 8, 8);
  gtk_widget_set_size_request (button_retour_16, 96, 29);

  alignment125 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment125);
  gtk_container_add (GTK_CONTAINER (button_retour_16), alignment125);

  hbox117 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox117);
  gtk_container_add (GTK_CONTAINER (alignment125), hbox117);

  image136 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image136);
  gtk_box_pack_start (GTK_BOX (hbox117), image136, FALSE, FALSE, 0);

  label316 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label316);
  gtk_box_pack_start (GTK_BOX (hbox117), label316, FALSE, FALSE, 0);

  quitter_mod = gtk_button_new ();
  gtk_widget_show (quitter_mod);
  gtk_fixed_put (GTK_FIXED (fixed25), quitter_mod, 656, 8);
  gtk_widget_set_size_request (quitter_mod, 88, 30);

  alignment126 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment126);
  gtk_container_add (GTK_CONTAINER (quitter_mod), alignment126);

  hbox118 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox118);
  gtk_container_add (GTK_CONTAINER (alignment126), hbox118);
  gtk_widget_set_size_request (hbox118, 74, 28);

  image137 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image137);
  gtk_box_pack_start (GTK_BOX (hbox118), image137, FALSE, FALSE, 0);

  label317 = gtk_label_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (label317);
  gtk_box_pack_start (GTK_BOX (hbox118), label317, FALSE, FALSE, 0);
  gtk_widget_set_size_request (label317, 55, -1);

  g_signal_connect ((gpointer) Annuler_modifie_BV, "clicked",
                    G_CALLBACK (on_Annuler_ajout_BV_clicked),
                    NULL);
  g_signal_connect ((gpointer) Enregistrer_modifie_BV, "clicked",
                    G_CALLBACK (on_Enregistrer_modifie_BV_clicked),
                    NULL);
  g_signal_connect ((gpointer) Verifier_modifie_BV, "clicked",
                    G_CALLBACK (on_Verifier_modifie_BV_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retour_16, "clicked",
                    G_CALLBACK (on_button_retour15_clicked),
                    NULL);
  g_signal_connect ((gpointer) quitter_mod, "clicked",
                    G_CALLBACK (on_quitter_mod_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label321), spinbutton_cb_modifie_BV);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label320), spinbutton_nb_modifie_BV);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label323), entry_id_AB_modifie_BV);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label319), entry_id_modifie_BV);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modifie_gest_BV, Modifie_gest_BV, "Modifie_gest_BV");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, fixed25, "fixed25");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, entry_id_modifie_BV, "entry_id_modifie_BV");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, label315, "label315");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, entry_id_AB_modifie_BV, "entry_id_AB_modifie_BV");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, spinbutton_cb_modifie_BV, "spinbutton_cb_modifie_BV");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, spinbutton_nb_modifie_BV, "spinbutton_nb_modifie_BV");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, label325, "label325");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, label321, "label321");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, label320, "label320");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, label322, "label322");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, label323, "label323");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, label319, "label319");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, combobox_modifie_BV, "combobox_modifie_BV");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, Annuler_modifie_BV, "Annuler_modifie_BV");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, alignment127, "alignment127");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, hbox119, "hbox119");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, image138, "image138");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, label318, "label318");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, Enregistrer_modifie_BV, "Enregistrer_modifie_BV");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, alignment128, "alignment128");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, hbox120, "hbox120");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, image139, "image139");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, label324, "label324");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, Verifier_modifie_BV, "Verifier_modifie_BV");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, alignment158, "alignment158");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, hbox150, "hbox150");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, image169, "image169");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, label375, "label375");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, button_retour_16, "button_retour_16");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, alignment125, "alignment125");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, hbox117, "hbox117");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, image136, "image136");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, label316, "label316");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, quitter_mod, "quitter_mod");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, alignment126, "alignment126");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, hbox118, "hbox118");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, image137, "image137");
  GLADE_HOOKUP_OBJECT (Modifie_gest_BV, label317, "label317");

  return Modifie_gest_BV;
}

GtkWidget*
create_Gestion_BV (void)
{
  GtkWidget *Gestion_BV;
  GtkWidget *fixed28;
  GtkWidget *label366;
  GtkWidget *entry_rechercher_gest_BV;
  GtkWidget *treeview_gest_BV;
  GtkWidget *button8;
  GtkWidget *alignment152;
  GtkWidget *hbox144;
  GtkWidget *image163;
  GtkWidget *label365;
  GtkWidget *Rechercher_gest_BV;
  GtkWidget *alignment153;
  GtkWidget *hbox145;
  GtkWidget *image164;
  GtkWidget *label367;
  GtkWidget *Modifier_gest_bv;
  GtkWidget *alignment156;
  GtkWidget *hbox148;
  GtkWidget *image167;
  GtkWidget *label370;
  GtkWidget *Supprimer_gest_bv;
  GtkWidget *alignment157;
  GtkWidget *hbox149;
  GtkWidget *image168;
  GtkWidget *label371;
  GtkWidget *ajouter_gest_bv;
  GtkWidget *alignment155;
  GtkWidget *hbox147;
  GtkWidget *image166;
  GtkWidget *label369;
  GtkWidget *label364;
  GtkWidget *Affiche_gest_BV;
  GtkWidget *alignment154;
  GtkWidget *hbox146;
  GtkWidget *image165;
  GtkWidget *label368;

  Gestion_BV = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Gestion_BV, 800, 544);
  gtk_window_set_title (GTK_WINDOW (Gestion_BV), _("Gestion_BV"));

  fixed28 = gtk_fixed_new ();
  gtk_widget_show (fixed28);
  gtk_container_add (GTK_CONTAINER (Gestion_BV), fixed28);

  label366 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">Identifiant:</span></b>         "));
  gtk_widget_show (label366);
  gtk_fixed_put (GTK_FIXED (fixed28), label366, 152, 96);
  gtk_widget_set_size_request (label366, 104, 33);
  gtk_label_set_use_markup (GTK_LABEL (label366), TRUE);

  entry_rechercher_gest_BV = gtk_entry_new ();
  gtk_widget_show (entry_rechercher_gest_BV);
  gtk_fixed_put (GTK_FIXED (fixed28), entry_rechercher_gest_BV, 256, 96);
  gtk_widget_set_size_request (entry_rechercher_gest_BV, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_rechercher_gest_BV), 8226);

  treeview_gest_BV = gtk_tree_view_new ();
  gtk_widget_show (treeview_gest_BV);
  gtk_fixed_put (GTK_FIXED (fixed28), treeview_gest_BV, 40, 152);
  gtk_widget_set_size_request (treeview_gest_BV, 584, 280);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview_gest_BV), TRUE);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_fixed_put (GTK_FIXED (fixed28), button8, 712, 8);
  gtk_widget_set_size_request (button8, 88, 30);

  alignment152 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment152);
  gtk_container_add (GTK_CONTAINER (button8), alignment152);

  hbox144 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox144);
  gtk_container_add (GTK_CONTAINER (alignment152), hbox144);

  image163 = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image163);
  gtk_box_pack_start (GTK_BOX (hbox144), image163, FALSE, FALSE, 0);

  label365 = gtk_label_new_with_mnemonic (_("  Quitter"));
  gtk_widget_show (label365);
  gtk_box_pack_start (GTK_BOX (hbox144), label365, FALSE, FALSE, 0);

  Rechercher_gest_BV = gtk_button_new ();
  gtk_widget_show (Rechercher_gest_BV);
  gtk_fixed_put (GTK_FIXED (fixed28), Rechercher_gest_BV, 456, 88);
  gtk_widget_set_size_request (Rechercher_gest_BV, 144, 40);

  alignment153 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment153);
  gtk_container_add (GTK_CONTAINER (Rechercher_gest_BV), alignment153);

  hbox145 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox145);
  gtk_container_add (GTK_CONTAINER (alignment153), hbox145);

  image164 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image164);
  gtk_box_pack_start (GTK_BOX (hbox145), image164, FALSE, FALSE, 0);

  label367 = gtk_label_new_with_mnemonic (_("  Recherche"));
  gtk_widget_show (label367);
  gtk_box_pack_start (GTK_BOX (hbox145), label367, FALSE, FALSE, 0);

  Modifier_gest_bv = gtk_button_new ();
  gtk_widget_show (Modifier_gest_bv);
  gtk_fixed_put (GTK_FIXED (fixed28), Modifier_gest_bv, 312, 504);
  gtk_widget_set_size_request (Modifier_gest_bv, 150, 40);

  alignment156 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment156);
  gtk_container_add (GTK_CONTAINER (Modifier_gest_bv), alignment156);

  hbox148 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox148);
  gtk_container_add (GTK_CONTAINER (alignment156), hbox148);

  image167 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image167);
  gtk_box_pack_start (GTK_BOX (hbox148), image167, FALSE, FALSE, 0);

  label370 = gtk_label_new_with_mnemonic (_("  <span color=\"blue\">Modifier</span>"));
  gtk_widget_show (label370);
  gtk_box_pack_start (GTK_BOX (hbox148), label370, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label370), TRUE);

  Supprimer_gest_bv = gtk_button_new ();
  gtk_widget_show (Supprimer_gest_bv);
  gtk_fixed_put (GTK_FIXED (fixed28), Supprimer_gest_bv, 520, 504);
  gtk_widget_set_size_request (Supprimer_gest_bv, 150, 40);

  alignment157 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment157);
  gtk_container_add (GTK_CONTAINER (Supprimer_gest_bv), alignment157);

  hbox149 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox149);
  gtk_container_add (GTK_CONTAINER (alignment157), hbox149);

  image168 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image168);
  gtk_box_pack_start (GTK_BOX (hbox149), image168, FALSE, FALSE, 0);

  label371 = gtk_label_new_with_mnemonic (_("  <span color=\"red\">Supprimer</span>"));
  gtk_widget_show (label371);
  gtk_box_pack_start (GTK_BOX (hbox149), label371, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label371), TRUE);

  ajouter_gest_bv = gtk_button_new ();
  gtk_widget_show (ajouter_gest_bv);
  gtk_fixed_put (GTK_FIXED (fixed28), ajouter_gest_bv, 112, 504);
  gtk_widget_set_size_request (ajouter_gest_bv, 150, 40);

  alignment155 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment155);
  gtk_container_add (GTK_CONTAINER (ajouter_gest_bv), alignment155);

  hbox147 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox147);
  gtk_container_add (GTK_CONTAINER (alignment155), hbox147);

  image166 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image166);
  gtk_box_pack_start (GTK_BOX (hbox147), image166, FALSE, FALSE, 0);

  label369 = gtk_label_new_with_mnemonic (_("  <span color=\"green\">Ajouter</span>"));
  gtk_widget_show (label369);
  gtk_box_pack_start (GTK_BOX (hbox147), label369, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label369), TRUE);

  label364 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">AFFICHAGE DES BUREAUX DE VOTE :</span></b>"));
  gtk_widget_show (label364);
  gtk_fixed_put (GTK_FIXED (fixed28), label364, 224, 8);
  gtk_widget_set_size_request (label364, 328, 40);
  gtk_label_set_use_markup (GTK_LABEL (label364), TRUE);

  Affiche_gest_BV = gtk_button_new ();
  gtk_widget_show (Affiche_gest_BV);
  gtk_fixed_put (GTK_FIXED (fixed28), Affiche_gest_BV, 640, 240);
  gtk_widget_set_size_request (Affiche_gest_BV, 152, 37);

  alignment154 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment154);
  gtk_container_add (GTK_CONTAINER (Affiche_gest_BV), alignment154);

  hbox146 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox146);
  gtk_container_add (GTK_CONTAINER (alignment154), hbox146);

  image165 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image165);
  gtk_box_pack_start (GTK_BOX (hbox146), image165, FALSE, FALSE, 0);

  label368 = gtk_label_new_with_mnemonic (_("   Actualiser"));
  gtk_widget_show (label368);
  gtk_box_pack_start (GTK_BOX (hbox146), label368, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) Gestion_BV, "focus_in_event",
                    G_CALLBACK (on_Gestion_BV_focus_in_event),
                    NULL);
  g_signal_connect ((gpointer) entry_rechercher_gest_BV, "changed",
                    G_CALLBACK (on_entry_rechercher_gest_BV_changed),
                    NULL);
  g_signal_connect ((gpointer) treeview_gest_BV, "row_activated",
                    G_CALLBACK (on_treeview_gest_BV_row_activated),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);
  g_signal_connect ((gpointer) Rechercher_gest_BV, "clicked",
                    G_CALLBACK (on_Rechercher_gest_BV_clicked),
                    NULL);
  g_signal_connect ((gpointer) Modifier_gest_bv, "clicked",
                    G_CALLBACK (on_Modifier_gest_bv_clicked),
                    NULL);
  g_signal_connect ((gpointer) Supprimer_gest_bv, "clicked",
                    G_CALLBACK (on_Supprimer_gest_bv_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter_gest_bv, "clicked",
                    G_CALLBACK (on_ajouter_gest_bv_clicked),
                    NULL);
  g_signal_connect ((gpointer) Affiche_gest_BV, "clicked",
                    G_CALLBACK (on_Affiche_gest_BV_clicked),
                    NULL);

  gtk_label_set_mnemonic_widget (GTK_LABEL (label366), entry_rechercher_gest_BV);
  gtk_label_set_mnemonic_widget (GTK_LABEL (label364), button8);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_BV, Gestion_BV, "Gestion_BV");
  GLADE_HOOKUP_OBJECT (Gestion_BV, fixed28, "fixed28");
  GLADE_HOOKUP_OBJECT (Gestion_BV, label366, "label366");
  GLADE_HOOKUP_OBJECT (Gestion_BV, entry_rechercher_gest_BV, "entry_rechercher_gest_BV");
  GLADE_HOOKUP_OBJECT (Gestion_BV, treeview_gest_BV, "treeview_gest_BV");
  GLADE_HOOKUP_OBJECT (Gestion_BV, button8, "button8");
  GLADE_HOOKUP_OBJECT (Gestion_BV, alignment152, "alignment152");
  GLADE_HOOKUP_OBJECT (Gestion_BV, hbox144, "hbox144");
  GLADE_HOOKUP_OBJECT (Gestion_BV, image163, "image163");
  GLADE_HOOKUP_OBJECT (Gestion_BV, label365, "label365");
  GLADE_HOOKUP_OBJECT (Gestion_BV, Rechercher_gest_BV, "Rechercher_gest_BV");
  GLADE_HOOKUP_OBJECT (Gestion_BV, alignment153, "alignment153");
  GLADE_HOOKUP_OBJECT (Gestion_BV, hbox145, "hbox145");
  GLADE_HOOKUP_OBJECT (Gestion_BV, image164, "image164");
  GLADE_HOOKUP_OBJECT (Gestion_BV, label367, "label367");
  GLADE_HOOKUP_OBJECT (Gestion_BV, Modifier_gest_bv, "Modifier_gest_bv");
  GLADE_HOOKUP_OBJECT (Gestion_BV, alignment156, "alignment156");
  GLADE_HOOKUP_OBJECT (Gestion_BV, hbox148, "hbox148");
  GLADE_HOOKUP_OBJECT (Gestion_BV, image167, "image167");
  GLADE_HOOKUP_OBJECT (Gestion_BV, label370, "label370");
  GLADE_HOOKUP_OBJECT (Gestion_BV, Supprimer_gest_bv, "Supprimer_gest_bv");
  GLADE_HOOKUP_OBJECT (Gestion_BV, alignment157, "alignment157");
  GLADE_HOOKUP_OBJECT (Gestion_BV, hbox149, "hbox149");
  GLADE_HOOKUP_OBJECT (Gestion_BV, image168, "image168");
  GLADE_HOOKUP_OBJECT (Gestion_BV, label371, "label371");
  GLADE_HOOKUP_OBJECT (Gestion_BV, ajouter_gest_bv, "ajouter_gest_bv");
  GLADE_HOOKUP_OBJECT (Gestion_BV, alignment155, "alignment155");
  GLADE_HOOKUP_OBJECT (Gestion_BV, hbox147, "hbox147");
  GLADE_HOOKUP_OBJECT (Gestion_BV, image166, "image166");
  GLADE_HOOKUP_OBJECT (Gestion_BV, label369, "label369");
  GLADE_HOOKUP_OBJECT (Gestion_BV, label364, "label364");
  GLADE_HOOKUP_OBJECT (Gestion_BV, Affiche_gest_BV, "Affiche_gest_BV");
  GLADE_HOOKUP_OBJECT (Gestion_BV, alignment154, "alignment154");
  GLADE_HOOKUP_OBJECT (Gestion_BV, hbox146, "hbox146");
  GLADE_HOOKUP_OBJECT (Gestion_BV, image165, "image165");
  GLADE_HOOKUP_OBJECT (Gestion_BV, label368, "label368");

  return Gestion_BV;
}

GtkWidget*
create_Login_BV (void)
{
  GtkWidget *Login_BV;
  GtkWidget *fixed31;
  GtkWidget *login_entry_identifiant;
  GtkWidget *login_entry_pass;
  GtkWidget *label376;
  GtkWidget *label377;
  GtkWidget *label379;
  GtkWidget *login_button_retour;
  GtkWidget *alignment160;
  GtkWidget *hbox152;
  GtkWidget *image171;
  GtkWidget *label381;
  GtkWidget *Connecter_gest_BV;
  GtkWidget *alignment159;
  GtkWidget *hbox151;
  GtkWidget *image170;
  GtkWidget *label378;
  GtkWidget *label_login;
  GtkWidget *label380;

  Login_BV = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Login_BV, 800, 544);
  gtk_window_set_title (GTK_WINDOW (Login_BV), _("Login"));

  fixed31 = gtk_fixed_new ();
  gtk_widget_show (fixed31);
  gtk_container_add (GTK_CONTAINER (Login_BV), fixed31);

  login_entry_identifiant = gtk_entry_new ();
  gtk_widget_show (login_entry_identifiant);
  gtk_fixed_put (GTK_FIXED (fixed31), login_entry_identifiant, 424, 168);
  gtk_widget_set_size_request (login_entry_identifiant, 168, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (login_entry_identifiant), 8226);

  login_entry_pass = gtk_entry_new ();
  gtk_widget_show (login_entry_pass);
  gtk_fixed_put (GTK_FIXED (fixed31), login_entry_pass, 424, 232);
  gtk_widget_set_size_request (login_entry_pass, 168, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (login_entry_pass), 8226);

  label376 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">Identifiant  :</span></b>"));
  gtk_widget_show (label376);
  gtk_fixed_put (GTK_FIXED (fixed31), label376, 248, 160);
  gtk_widget_set_size_request (label376, 120, 49);
  gtk_label_set_use_markup (GTK_LABEL (label376), TRUE);

  label377 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">Mot de passe  :</span></b>"));
  gtk_widget_show (label377);
  gtk_fixed_put (GTK_FIXED (fixed31), label377, 256, 224);
  gtk_widget_set_size_request (label377, 128, 49);
  gtk_label_set_use_markup (GTK_LABEL (label377), TRUE);

  label379 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">Authentification</span></b>"));
  gtk_widget_show (label379);
  gtk_fixed_put (GTK_FIXED (fixed31), label379, 272, 56);
  gtk_widget_set_size_request (label379, 272, 49);
  gtk_label_set_use_markup (GTK_LABEL (label379), TRUE);

  login_button_retour = gtk_button_new ();
  gtk_widget_show (login_button_retour);
  gtk_fixed_put (GTK_FIXED (fixed31), login_button_retour, 16, 16);
  gtk_widget_set_size_request (login_button_retour, 104, 37);

  alignment160 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment160);
  gtk_container_add (GTK_CONTAINER (login_button_retour), alignment160);

  hbox152 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox152);
  gtk_container_add (GTK_CONTAINER (alignment160), hbox152);

  image171 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image171);
  gtk_box_pack_start (GTK_BOX (hbox152), image171, FALSE, FALSE, 0);

  label381 = gtk_label_new_with_mnemonic (_("  Retoure"));
  gtk_widget_show (label381);
  gtk_box_pack_start (GTK_BOX (hbox152), label381, FALSE, FALSE, 0);

  Connecter_gest_BV = gtk_button_new ();
  gtk_widget_show (Connecter_gest_BV);
  gtk_fixed_put (GTK_FIXED (fixed31), Connecter_gest_BV, 336, 360);
  gtk_widget_set_size_request (Connecter_gest_BV, 152, 45);

  alignment159 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment159);
  gtk_container_add (GTK_CONTAINER (Connecter_gest_BV), alignment159);

  hbox151 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox151);
  gtk_container_add (GTK_CONTAINER (alignment159), hbox151);

  image170 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image170);
  gtk_box_pack_start (GTK_BOX (hbox151), image170, FALSE, FALSE, 0);

  label378 = gtk_label_new_with_mnemonic (_("  <b><span color=\"green\">Se connecter</span></b>"));
  gtk_widget_show (label378);
  gtk_box_pack_start (GTK_BOX (hbox151), label378, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label378), TRUE);

  label_login = gtk_label_new ("");
  gtk_widget_show (label_login);
  gtk_fixed_put (GTK_FIXED (fixed31), label_login, 280, 296);
  gtk_widget_set_size_request (label_login, 272, 41);

  label380 = gtk_label_new_with_mnemonic (_("<b><span color=\"black\">Gestion Bureau de Vote</span></b>"));
  gtk_widget_show (label380);
  gtk_fixed_put (GTK_FIXED (fixed31), label380, 264, 0);
  gtk_widget_set_size_request (label380, 272, 49);
  gtk_label_set_use_markup (GTK_LABEL (label380), TRUE);

  g_signal_connect ((gpointer) login_button_retour, "clicked",
                    G_CALLBACK (on_login_button_retour_clicked),
                    NULL);
  g_signal_connect ((gpointer) Connecter_gest_BV, "clicked",
                    G_CALLBACK (on_Connecter_gest_BV_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Login_BV, Login_BV, "Login_BV");
  GLADE_HOOKUP_OBJECT (Login_BV, fixed31, "fixed31");
  GLADE_HOOKUP_OBJECT (Login_BV, login_entry_identifiant, "login_entry_identifiant");
  GLADE_HOOKUP_OBJECT (Login_BV, login_entry_pass, "login_entry_pass");
  GLADE_HOOKUP_OBJECT (Login_BV, label376, "label376");
  GLADE_HOOKUP_OBJECT (Login_BV, label377, "label377");
  GLADE_HOOKUP_OBJECT (Login_BV, label379, "label379");
  GLADE_HOOKUP_OBJECT (Login_BV, login_button_retour, "login_button_retour");
  GLADE_HOOKUP_OBJECT (Login_BV, alignment160, "alignment160");
  GLADE_HOOKUP_OBJECT (Login_BV, hbox152, "hbox152");
  GLADE_HOOKUP_OBJECT (Login_BV, image171, "image171");
  GLADE_HOOKUP_OBJECT (Login_BV, label381, "label381");
  GLADE_HOOKUP_OBJECT (Login_BV, Connecter_gest_BV, "Connecter_gest_BV");
  GLADE_HOOKUP_OBJECT (Login_BV, alignment159, "alignment159");
  GLADE_HOOKUP_OBJECT (Login_BV, hbox151, "hbox151");
  GLADE_HOOKUP_OBJECT (Login_BV, image170, "image170");
  GLADE_HOOKUP_OBJECT (Login_BV, label378, "label378");
  GLADE_HOOKUP_OBJECT (Login_BV, label_login, "label_login");
  GLADE_HOOKUP_OBJECT (Login_BV, label380, "label380");

  return Login_BV;
}

GtkWidget*
create_Accueil (void)
{
  GtkWidget *Accueil;
  GtkWidget *fixed32;
  GtkWidget *Accueil_EO;
  GtkWidget *alignment165;
  GtkWidget *hbox157;
  GtkWidget *image176;
  GtkWidget *label386;
  GtkWidget *Accueil_EC;
  GtkWidget *alignment164;
  GtkWidget *hbox156;
  GtkWidget *image175;
  GtkWidget *label385;
  GtkWidget *Accueil_AB;
  GtkWidget *alignment163;
  GtkWidget *hbox155;
  GtkWidget *image174;
  GtkWidget *label384;
  GtkWidget *Accueil_EE;
  GtkWidget *alignment162;
  GtkWidget *hbox154;
  GtkWidget *image173;
  GtkWidget *label383;
  GtkWidget *Accueil_EA;
  GtkWidget *alignment161;
  GtkWidget *hbox153;
  GtkWidget *image172;
  GtkWidget *label382;

  Accueil = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Accueil, 800, 544);
  gtk_window_set_title (GTK_WINDOW (Accueil), _("Accueil"));

  fixed32 = gtk_fixed_new ();
  gtk_widget_show (fixed32);
  gtk_container_add (GTK_CONTAINER (Accueil), fixed32);

  Accueil_EO = gtk_button_new ();
  gtk_widget_show (Accueil_EO);
  gtk_fixed_put (GTK_FIXED (fixed32), Accueil_EO, 224, 376);
  gtk_widget_set_size_request (Accueil_EO, 384, 53);

  alignment165 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment165);
  gtk_container_add (GTK_CONTAINER (Accueil_EO), alignment165);

  hbox157 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox157);
  gtk_container_add (GTK_CONTAINER (alignment165), hbox157);

  image176 = gtk_image_new_from_stock ("gtk-justify-center", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image176);
  gtk_box_pack_start (GTK_BOX (hbox157), image176, FALSE, FALSE, 0);

  label386 = gtk_label_new_with_mnemonic (_("  <b><span color=\"red\">Gestion d'Observateur</span></b>    "));
  gtk_widget_show (label386);
  gtk_box_pack_start (GTK_BOX (hbox157), label386, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label386), TRUE);

  Accueil_EC = gtk_button_new ();
  gtk_widget_show (Accueil_EC);
  gtk_fixed_put (GTK_FIXED (fixed32), Accueil_EC, 224, 296);
  gtk_widget_set_size_request (Accueil_EC, 384, 53);

  alignment164 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment164);
  gtk_container_add (GTK_CONTAINER (Accueil_EC), alignment164);

  hbox156 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox156);
  gtk_container_add (GTK_CONTAINER (alignment164), hbox156);

  image175 = gtk_image_new_from_stock ("gtk-justify-center", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image175);
  gtk_box_pack_start (GTK_BOX (hbox156), image175, FALSE, FALSE, 0);

  label385 = gtk_label_new_with_mnemonic (_("  <b><span color=\"red\">Espace Candidat</span></b>    "));
  gtk_widget_show (label385);
  gtk_box_pack_start (GTK_BOX (hbox156), label385, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label385), TRUE);

  Accueil_AB = gtk_button_new ();
  gtk_widget_show (Accueil_AB);
  gtk_fixed_put (GTK_FIXED (fixed32), Accueil_AB, 224, 216);
  gtk_widget_set_size_request (Accueil_AB, 384, 53);

  alignment163 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment163);
  gtk_container_add (GTK_CONTAINER (Accueil_AB), alignment163);

  hbox155 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox155);
  gtk_container_add (GTK_CONTAINER (alignment163), hbox155);

  image174 = gtk_image_new_from_stock ("gtk-justify-center", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image174);
  gtk_box_pack_start (GTK_BOX (hbox155), image174, FALSE, FALSE, 0);

  label384 = gtk_label_new_with_mnemonic (_("  <b><span color=\"red\">Gestion Agent de Bureau de Vote</span></b>    "));
  gtk_widget_show (label384);
  gtk_box_pack_start (GTK_BOX (hbox155), label384, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label384), TRUE);

  Accueil_EE = gtk_button_new ();
  gtk_widget_show (Accueil_EE);
  gtk_fixed_put (GTK_FIXED (fixed32), Accueil_EE, 224, 144);
  gtk_widget_set_size_request (Accueil_EE, 384, 53);

  alignment162 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment162);
  gtk_container_add (GTK_CONTAINER (Accueil_EE), alignment162);

  hbox154 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox154);
  gtk_container_add (GTK_CONTAINER (alignment162), hbox154);

  image173 = gtk_image_new_from_stock ("gtk-justify-center", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image173);
  gtk_box_pack_start (GTK_BOX (hbox154), image173, FALSE, FALSE, 0);

  label383 = gtk_label_new_with_mnemonic (_("  <b><span color=\"red\">Espace Electeur</span></b>    "));
  gtk_widget_show (label383);
  gtk_box_pack_start (GTK_BOX (hbox154), label383, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label383), TRUE);

  Accueil_EA = gtk_button_new ();
  gtk_widget_show (Accueil_EA);
  gtk_fixed_put (GTK_FIXED (fixed32), Accueil_EA, 224, 64);
  gtk_widget_set_size_request (Accueil_EA, 384, 53);

  alignment161 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment161);
  gtk_container_add (GTK_CONTAINER (Accueil_EA), alignment161);

  hbox153 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox153);
  gtk_container_add (GTK_CONTAINER (alignment161), hbox153);

  image172 = gtk_image_new_from_stock ("gtk-justify-center", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image172);
  gtk_box_pack_start (GTK_BOX (hbox153), image172, FALSE, FALSE, 0);

  label382 = gtk_label_new_with_mnemonic (_("  <b><span color=\"red\">Espace Administrateur</span></b>    "));
  gtk_widget_show (label382);
  gtk_box_pack_start (GTK_BOX (hbox153), label382, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label382), TRUE);

  g_signal_connect ((gpointer) Accueil_EO, "clicked",
                    G_CALLBACK (on_Accueil_EO_clicked),
                    NULL);
  g_signal_connect ((gpointer) Accueil_EC, "clicked",
                    G_CALLBACK (on_Accueil_EC_clicked),
                    NULL);
  g_signal_connect ((gpointer) Accueil_AB, "clicked",
                    G_CALLBACK (on_Accueil_AB_clicked),
                    NULL);
  g_signal_connect ((gpointer) Accueil_EE, "clicked",
                    G_CALLBACK (on_Accueil_EE_clicked),
                    NULL);
  g_signal_connect ((gpointer) Accueil_EA, "clicked",
                    G_CALLBACK (on_Accueil_EA_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Accueil, Accueil, "Accueil");
  GLADE_HOOKUP_OBJECT (Accueil, fixed32, "fixed32");
  GLADE_HOOKUP_OBJECT (Accueil, Accueil_EO, "Accueil_EO");
  GLADE_HOOKUP_OBJECT (Accueil, alignment165, "alignment165");
  GLADE_HOOKUP_OBJECT (Accueil, hbox157, "hbox157");
  GLADE_HOOKUP_OBJECT (Accueil, image176, "image176");
  GLADE_HOOKUP_OBJECT (Accueil, label386, "label386");
  GLADE_HOOKUP_OBJECT (Accueil, Accueil_EC, "Accueil_EC");
  GLADE_HOOKUP_OBJECT (Accueil, alignment164, "alignment164");
  GLADE_HOOKUP_OBJECT (Accueil, hbox156, "hbox156");
  GLADE_HOOKUP_OBJECT (Accueil, image175, "image175");
  GLADE_HOOKUP_OBJECT (Accueil, label385, "label385");
  GLADE_HOOKUP_OBJECT (Accueil, Accueil_AB, "Accueil_AB");
  GLADE_HOOKUP_OBJECT (Accueil, alignment163, "alignment163");
  GLADE_HOOKUP_OBJECT (Accueil, hbox155, "hbox155");
  GLADE_HOOKUP_OBJECT (Accueil, image174, "image174");
  GLADE_HOOKUP_OBJECT (Accueil, label384, "label384");
  GLADE_HOOKUP_OBJECT (Accueil, Accueil_EE, "Accueil_EE");
  GLADE_HOOKUP_OBJECT (Accueil, alignment162, "alignment162");
  GLADE_HOOKUP_OBJECT (Accueil, hbox154, "hbox154");
  GLADE_HOOKUP_OBJECT (Accueil, image173, "image173");
  GLADE_HOOKUP_OBJECT (Accueil, label383, "label383");
  GLADE_HOOKUP_OBJECT (Accueil, Accueil_EA, "Accueil_EA");
  GLADE_HOOKUP_OBJECT (Accueil, alignment161, "alignment161");
  GLADE_HOOKUP_OBJECT (Accueil, hbox153, "hbox153");
  GLADE_HOOKUP_OBJECT (Accueil, image172, "image172");
  GLADE_HOOKUP_OBJECT (Accueil, label382, "label382");

  return Accueil;
}

GtkWidget*
create_Administrateur (void)
{
  GtkWidget *Administrateur;
  GtkWidget *fixed33;
  GtkWidget *admin_GE;
  GtkWidget *alignment167;
  GtkWidget *hbox159;
  GtkWidget *image178;
  GtkWidget *label388;
  GtkWidget *admin_GU;
  GtkWidget *alignment169;
  GtkWidget *hbox161;
  GtkWidget *image180;
  GtkWidget *label390;
  GtkWidget *admin_stat;
  GtkWidget *alignment170;
  GtkWidget *hbox162;
  GtkWidget *image181;
  GtkWidget *label391;
  GtkWidget *admin_GB;
  GtkWidget *alignment168;
  GtkWidget *hbox160;
  GtkWidget *image179;
  GtkWidget *label389;
  GtkWidget *admin_retour;
  GtkWidget *alignment166;
  GtkWidget *hbox158;
  GtkWidget *image177;
  GtkWidget *label387;

  Administrateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (Administrateur, 800, 544);
  gtk_window_set_title (GTK_WINDOW (Administrateur), _("window2"));

  fixed33 = gtk_fixed_new ();
  gtk_widget_show (fixed33);
  gtk_container_add (GTK_CONTAINER (Administrateur), fixed33);

  admin_GE = gtk_button_new ();
  gtk_widget_show (admin_GE);
  gtk_fixed_put (GTK_FIXED (fixed33), admin_GE, 232, 88);
  gtk_widget_set_size_request (admin_GE, 384, 53);

  alignment167 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment167);
  gtk_container_add (GTK_CONTAINER (admin_GE), alignment167);

  hbox159 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox159);
  gtk_container_add (GTK_CONTAINER (alignment167), hbox159);

  image178 = gtk_image_new_from_stock ("gtk-directory", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image178);
  gtk_box_pack_start (GTK_BOX (hbox159), image178, FALSE, FALSE, 0);

  label388 = gtk_label_new_with_mnemonic (_("  <b><span color=\"black\">Gestion des Elections</span></b>"));
  gtk_widget_show (label388);
  gtk_box_pack_start (GTK_BOX (hbox159), label388, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label388), TRUE);

  admin_GU = gtk_button_new ();
  gtk_widget_show (admin_GU);
  gtk_fixed_put (GTK_FIXED (fixed33), admin_GU, 232, 296);
  gtk_widget_set_size_request (admin_GU, 384, 53);

  alignment169 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment169);
  gtk_container_add (GTK_CONTAINER (admin_GU), alignment169);

  hbox161 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox161);
  gtk_container_add (GTK_CONTAINER (alignment169), hbox161);

  image180 = gtk_image_new_from_stock ("gtk-directory", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image180);
  gtk_box_pack_start (GTK_BOX (hbox161), image180, FALSE, FALSE, 0);

  label390 = gtk_label_new_with_mnemonic (_("  <b><span color=\"black\">Gestion d'Utilisateur</span></b>"));
  gtk_widget_show (label390);
  gtk_box_pack_start (GTK_BOX (hbox161), label390, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label390), TRUE);

  admin_stat = gtk_button_new ();
  gtk_widget_show (admin_stat);
  gtk_fixed_put (GTK_FIXED (fixed33), admin_stat, 232, 400);
  gtk_widget_set_size_request (admin_stat, 384, 53);

  alignment170 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment170);
  gtk_container_add (GTK_CONTAINER (admin_stat), alignment170);

  hbox162 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox162);
  gtk_container_add (GTK_CONTAINER (alignment170), hbox162);

  image181 = gtk_image_new_from_stock ("gtk-page-setup", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image181);
  gtk_box_pack_start (GTK_BOX (hbox162), image181, FALSE, FALSE, 0);

  label391 = gtk_label_new_with_mnemonic (_("  <b><span color=\"black\">Statistique</span></b>"));
  gtk_widget_show (label391);
  gtk_box_pack_start (GTK_BOX (hbox162), label391, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label391), TRUE);

  admin_GB = gtk_button_new ();
  gtk_widget_show (admin_GB);
  gtk_fixed_put (GTK_FIXED (fixed33), admin_GB, 232, 192);
  gtk_widget_set_size_request (admin_GB, 384, 53);

  alignment168 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment168);
  gtk_container_add (GTK_CONTAINER (admin_GB), alignment168);

  hbox160 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox160);
  gtk_container_add (GTK_CONTAINER (alignment168), hbox160);

  image179 = gtk_image_new_from_stock ("gtk-directory", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image179);
  gtk_box_pack_start (GTK_BOX (hbox160), image179, FALSE, FALSE, 0);

  label389 = gtk_label_new_with_mnemonic (_("  <b><span color=\"black\">Gestion Bureau de Vote</span></b>"));
  gtk_widget_show (label389);
  gtk_box_pack_start (GTK_BOX (hbox160), label389, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label389), TRUE);

  admin_retour = gtk_button_new ();
  gtk_widget_show (admin_retour);
  gtk_fixed_put (GTK_FIXED (fixed33), admin_retour, 24, 16);
  gtk_widget_set_size_request (admin_retour, 104, 29);

  alignment166 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment166);
  gtk_container_add (GTK_CONTAINER (admin_retour), alignment166);

  hbox158 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox158);
  gtk_container_add (GTK_CONTAINER (alignment166), hbox158);

  image177 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image177);
  gtk_box_pack_start (GTK_BOX (hbox158), image177, FALSE, FALSE, 0);

  label387 = gtk_label_new_with_mnemonic (_("  Retour"));
  gtk_widget_show (label387);
  gtk_box_pack_start (GTK_BOX (hbox158), label387, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) admin_GE, "clicked",
                    G_CALLBACK (on_admin_GE_clicked),
                    NULL);
  g_signal_connect ((gpointer) admin_GU, "clicked",
                    G_CALLBACK (on_admin_GU_clicked),
                    NULL);
  g_signal_connect ((gpointer) admin_GB, "clicked",
                    G_CALLBACK (on_admin_GB_clicked),
                    NULL);
  g_signal_connect ((gpointer) admin_retour, "clicked",
                    G_CALLBACK (on_admin_retour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Administrateur, Administrateur, "Administrateur");
  GLADE_HOOKUP_OBJECT (Administrateur, fixed33, "fixed33");
  GLADE_HOOKUP_OBJECT (Administrateur, admin_GE, "admin_GE");
  GLADE_HOOKUP_OBJECT (Administrateur, alignment167, "alignment167");
  GLADE_HOOKUP_OBJECT (Administrateur, hbox159, "hbox159");
  GLADE_HOOKUP_OBJECT (Administrateur, image178, "image178");
  GLADE_HOOKUP_OBJECT (Administrateur, label388, "label388");
  GLADE_HOOKUP_OBJECT (Administrateur, admin_GU, "admin_GU");
  GLADE_HOOKUP_OBJECT (Administrateur, alignment169, "alignment169");
  GLADE_HOOKUP_OBJECT (Administrateur, hbox161, "hbox161");
  GLADE_HOOKUP_OBJECT (Administrateur, image180, "image180");
  GLADE_HOOKUP_OBJECT (Administrateur, label390, "label390");
  GLADE_HOOKUP_OBJECT (Administrateur, admin_stat, "admin_stat");
  GLADE_HOOKUP_OBJECT (Administrateur, alignment170, "alignment170");
  GLADE_HOOKUP_OBJECT (Administrateur, hbox162, "hbox162");
  GLADE_HOOKUP_OBJECT (Administrateur, image181, "image181");
  GLADE_HOOKUP_OBJECT (Administrateur, label391, "label391");
  GLADE_HOOKUP_OBJECT (Administrateur, admin_GB, "admin_GB");
  GLADE_HOOKUP_OBJECT (Administrateur, alignment168, "alignment168");
  GLADE_HOOKUP_OBJECT (Administrateur, hbox160, "hbox160");
  GLADE_HOOKUP_OBJECT (Administrateur, image179, "image179");
  GLADE_HOOKUP_OBJECT (Administrateur, label389, "label389");
  GLADE_HOOKUP_OBJECT (Administrateur, admin_retour, "admin_retour");
  GLADE_HOOKUP_OBJECT (Administrateur, alignment166, "alignment166");
  GLADE_HOOKUP_OBJECT (Administrateur, hbox158, "hbox158");
  GLADE_HOOKUP_OBJECT (Administrateur, image177, "image177");
  GLADE_HOOKUP_OBJECT (Administrateur, label387, "label387");

  return Administrateur;
}

